server.port: 8080
spring.application.name: user-service
spring.config.import: 'optional:configserver:http://localhost:8888'

# Datasource
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/august?currentSchema=springboot_msa
spring.datasource.username: kalgooksoo
spring.datasource.password: 1234

spring.jpa.open-in-view: true
spring.jpa.show-sql: true
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: update

logging.level:
  org.hibernate.type.descriptor.jdbc.BasicBinder: trace

management.endpoints.web.exposure.include: "*"