server.port: 8080
spring.profiles.active: default
spring:
  application:
    name: user-service
  config:
    import: 'optional:configserver:http://localhost:8888'
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.show-sql: true

logging:
  level:
    org.hibernate.type.descriptor.jdbc.BasicBinder: TRACE

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: update

management.endpoints.web.exposure.include: "*"