server:
  port: 8060

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**