server:
  port: 8060

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/authorization/**
#        - id: employee-service
#          uri: lb://employee-service
#          predicates:
#            - Path=/employee/**
#        - id: department-service
#          uri: lb://department-service
#          predicates:
#            - Path=/department/**
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#            - Path=/manager/**
#            - Path=/admin/**
#            - Path=/sign-in
#        - id: mail-service
#          uri: lb://mail-service
#          predicates:
#            - Path=/mail/**