server.port: 8081
spring.application.name: security-service
spring.config.import: 'optional:configserver:http://localhost:8888'

logging.level:
  org.hibernate.type.descriptor.jdbc.BasicBinder: trace

jwt:
  secret: security
  expiration-milli-seconds: 1800000